application: barxiv
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /cache
  static_dir: cache

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /apple-touch-icon.png
  static_files: images/apple-touch-icon.png
  upload: images/apple-touch-icon.png

- url: /admin/.*
  script: barxiv.application
  login: admin

- url: /instant/.*
  script: barxiv.application

- url: /abstract/.*
  script: barxiv.application

- url: /.*
  script: barxiv.application

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

